import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  MinLength,
} from 'class-validator';
import { SiteEventType } from '@prisma/client';

export class TrackEventDto {
  @IsEnum(SiteEventType)
  type!: SiteEventType;

  @IsOptional()
  @IsString()
  @MaxLength(200)
  page?: string;

  // Random non-personal token generated by the browser (localStorage).
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  visitorId!: string;
}
